### ISSUE TITLE
Support default parameter syntax

### ISSUE THREAD

**Issue by binarykitchen** [bitoffog/rollup-plugin-regenerator#2]
When I am trying to bundle test files with rollup and your plugin I am seeing this error:

```
└─( 2 ) ❱❱❱ yarn test                                                                        1 ⏎  +2658 18:38 ❰─┘
yarn test v0.27.5
$ rollup -c env/test/rollup.config.js | tape-run
🚨   (regenerator plugin) Line 523: Unexpected token =
node_modules/zora/dist/zora.es.js

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: javascript required
    at Stream.<anonymous> (/home/michael-heuberger/code/videomail-client/node_modules/browser-run/index.js:35:34)
    at _end (/home/michael-heuberger/code/videomail-client/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/michael-heuberger/code/videomail-client/node_modules/through/index.js:74:5)
    at Stream.method [as end] (/home/michael-heuberger/code/videomail-client/node_modules/duplexer/index.js:47:39)
    at Stream.<anonymous> (/home/michael-heuberger/code/videomail-client/node_modules/throughout/index.js:7:25)
    at _end (/home/michael-heuberger/code/videomail-client/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/michael-heuberger/code/videomail-client/node_modules/through/index.js:74:5)
    at Stream.onend (internal/streams/legacy.js:44:10)
    at emitNone (events.js:110:20)
    at Stream.emit (events.js:207:7)
error Command failed with exit code 1.
```

Looks like your plugin does not understand the default parameter syntax from the ecmascript2016 spec. I have this initially reported in https://github.com/lorenzofox3/zora/issues/4 but would like to double check with you first ...

**Comment by serg-plusplus** [comment]
The answer to this question is here: [lorenzofox3/zora#4](https://github.com/lorenzofox3/zora/issues/4)
